### ISSUE TITLE
Improve Date Calculation Method for DateTimeRange

### ISSUE THREAD

**Issue by batuhanseckinnn** [Robertrobinson777/dropdown_date_picker#18]
Hello,

I would like to suggest an improvement for the date calculation method in the DateTimeRange class.

Here is a more accurate and concise method for calculating the number of days in a given month:

int daysInMonth(int year, int month) {
  DateTime from = DateTime(year, month, 1);
  DateTime to = DateTime(year, month + 1, 1);
  return (to.difference(from).inHours / 24).round();
}

I believe this enhancement will improve the accuracy and reliability of date-related operations within the library.

Thank you for considering this suggestion.

**Comment by Robertrobinson777** [comment]
optimized in commit #59256a9
