### ISSUE TITLE
Please link `pub.dev` package listing on GitHub landing page

### ISSUE THREAD

**Issue by domesticmouse** [Robertrobinson777/dropdown_date_picker#4]
Please add [`pub.dev/packages/datepicker_dropdown`](https://pub.dev/packages/datepicker_dropdown) to the GitHub description to link to the pub.dev listing for this Widget on [`github.com/Robertrobinson777/dropdown_date_picker`](https://github.com/Robertrobinson777/dropdown_date_picker) landing page. Thanks!

**Comment by Robertrobinson777** [comment]
Thank you @domesticmouse
